pipeline {
   agent {
  label 'Devserver'
}

    stages {
        stage('Build')
        {
            steps {
                sh 'mvn clean package'
            }

        post {
  success {
        archiveArtifacts artifacts: '**/target/*.war'
           }
        }


        }
        
    }
}
