pipeline{
    agent {
  label 'Devserver'
}
tools {
  maven 'my-maven'
}
environment {
  Name = "Shalini"
}
parameters {
  string defaultValue: 'Bhupathi', name: 'LastName'
}
stages{
    stage('build')
    {
        steps {
        sh "mvn clean package"
        echo "hello $Name ${params.LastName}"
        } 
       
    }
stage('test')
{
    parallel {
        stage ('testA')
        {
            steps{
           echo " this is test A"
           }
        }
        stage ('testB')
        {
            steps{
            echo "this is test B"
            }
        }

    post {
  success {
    archiveArtifacts artifacts: "**/target/*.jar"
  }
}
   
}

    
}

}
}