pipeline{
    agent {
  label 'Devserver'
}
tools {
  maven 'my-maven'
}


stages{
    stage('build')
    {
        steps {
        sh "mvn clean package"
        } 
        post {
  success {
    archiveArtifacts artifacts: "**/target/*.jar"
  }
}
    }
    
    
}

}